language: R
cache: packages

before_install:
  - "curl https://xran.yihui.org/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl https://xran.yihui.org/r-xran | bash)"
  - cd inst/examples; ./deploy_github
